### ISSUE TITLE
Sleep time

### ISSUE THREAD

**Issue by a-person-lol** [a-person-lol/spammer#1]
So the sleep time is also the same as the starting time loop. This means if you set the sleep time below 1 second, it will start way too fast. I have explained in my release why I can't fix it until 19th September 2023.

A quick fix for this is to set sleep time to 1 second or more. Your messages will be spammed slow though.

**Comment by DevHacker24** [comment]
not on 19th my pc still broke

**Comment by a-person-lol** [comment]
fixed in v2
